### ISSUE TITLE
The big picture

### ISSUE THREAD

**Issue by valentinogagliardi** [Dhn149/CSharpExercises#7]
Now that you have all the classes in place, in `Program.Main`, write the logic to fullfill the following requirements:

### Milestone 1

- [x] we can create new customers
- [x] we can create new articles
- [x] we can add each article to `Articles`
- [x] we can list all the articles (printing to console is enough)

### Milestone 2

- [x] we can search for an article by its description, and we can print its price
- [x] we can add the searched article to the Cart

### Milestone 3

- [x] we can add multiple articles to the cart
- [ ] we can provide the user with a total price of all the articles in the cart

Hints: `List` methods - `foreach` - LINQ
